# Generated by Django 6.1.1 on 2026-09-04 04:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'reserva de spa',
                'verbose_name_plural': 'reservas de spa',
                'db_table': 'spa_bookings',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='WineOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'pedido de vinos',
                'verbose_name_plural': 'pedidos de vinos',
                'db_table': 'wine_orders',
            },
        ),
        migrations.CreateModel(
            name='WineOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'línea de pedido de vinos',
                'verbose_name_plural': 'líneas de pedido de vinos',
                'db_table': 'wine_order_items',
            },
        ),
        migrations.CreateModel(
            name='FoodBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Cena', 'Cena')], max_length=20)),
                ('guests_count', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='servicios.foodmenu')),
            ],
            options={
                'verbose_name': 'reserva de comida',
                'verbose_name_plural': 'reservas de comida',
                'db_table': 'food_bookings',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('payment_status', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('completado', 'Completado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fare_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='propiedades.faretype')),
            ],
            options={
                'verbose_name': 'reservación',
                'verbose_name_plural': 'reservaciones',
                'db_table': 'reservations',
                'ordering': ['check_in'],
            },
        ),
    ]
