# Generated by Django 6.1.1 on 2026-09-04 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
        ('reservaciones', '0001_initial'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodbooking',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_bookings', to='reservaciones.reservation'),
        ),
        migrations.AddField(
            model_name='spabooking',
            name='masseuse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='proveedores.spamasseuse'),
        ),
        migrations.AddField(
            model_name='spabooking',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spa_bookings', to='reservaciones.reservation'),
        ),
        migrations.AddField(
            model_name='wineorder',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wine_orders', to='reservaciones.reservation'),
        ),
        migrations.AddField(
            model_name='wineorderitem',
            name='wine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='servicios.wine'),
        ),
        migrations.AddField(
            model_name='wineorderitem',
            name='wine_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservaciones.wineorder'),
        ),
        migrations.AddField(
            model_name='wineorderitem',
            name='wine_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='servicios.winepackage'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['guest'], name='reservations_guest_id_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['fare_type'], name='reservations_fare_type_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'check_in'], name='reservations_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='reservations_check_out_after_check_in', violation_error_message='La fecha de salida debe ser posterior a la de entrada.'),
        ),
        migrations.AddIndex(
            model_name='foodbooking',
            index=models.Index(fields=['reservation'], name='food_bookings_reservation_idx'),
        ),
        migrations.AddIndex(
            model_name='foodbooking',
            index=models.Index(fields=['menu'], name='food_bookings_menu_idx'),
        ),
        migrations.AddConstraint(
            model_name='foodbooking',
            constraint=models.CheckConstraint(condition=models.Q(('guests_count__gt', 0)), name='food_bookings_guests_count_positive', violation_error_message='El número de comensales debe ser mayor a cero.'),
        ),
        migrations.AddIndex(
            model_name='spabooking',
            index=models.Index(fields=['reservation'], name='spa_bookings_reservation_idx'),
        ),
        migrations.AddIndex(
            model_name='spabooking',
            index=models.Index(fields=['masseuse', 'date', 'time'], name='spa_bookings_masseuse_slot_idx'),
        ),
        migrations.AddIndex(
            model_name='wineorder',
            index=models.Index(fields=['reservation'], name='wine_orders_reservation_idx'),
        ),
        migrations.AddIndex(
            model_name='wineorderitem',
            index=models.Index(fields=['wine_order'], name='wine_order_items_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='wineorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='wine_order_items_quantity_positive', violation_error_message='La cantidad debe ser mayor a cero.'),
        ),
        migrations.AddConstraint(
            model_name='wineorderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('wine__isnull', False), ('wine_package__isnull', True)), models.Q(('wine__isnull', True), ('wine_package__isnull', False)), _connector='OR'), name='wine_order_items_exactly_one_product', violation_error_message='Cada línea debe referir una botella o un paquete, no ambos.'),
        ),
    ]
