# Generated by Django 6.1.1 on 2026-09-08 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_supplierprofile_property_propertyaccessgrant'),
        ('reservaciones', '0004_tenant_zero_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='propiedades.property'),
        ),
    ]
