# Generated by Django 6.1.1 on 2026-09-04 04:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaMasseuse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('invitado', 'Invitado')], default='activo', max_length=10)),
            ],
            options={
                'verbose_name': 'masajista',
                'verbose_name_plural': 'masajistas',
                'db_table': 'spa_masseuses',
                'ordering': ['name'],
            },
        ),
    ]
