[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rafael Hernandez", email = "a00836774@tec.mx" }
]
requires-python = ">=3.12"
dependencies = [
    "django>=6.1.1",
    "django-cors-headers>=4.9.0",
    "djangorestframework>=3.18.0",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.30.0",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
