# Generated by Django 6.1.1 on 2026-09-04 04:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('sort_order', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoría de amenidades',
                'verbose_name_plural': 'categorías de amenidades',
                'db_table': 'amenity_categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FareType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('surcharge_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'tipo de tarifa',
                'verbose_name_plural': 'tipos de tarifa',
                'db_table': 'fare_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('label', models.TextField()),
                ('sort_order', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'foto de la propiedad',
                'verbose_name_plural': 'fotos de la propiedad',
                'db_table': 'property_photos',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PropertySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nightly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'configuración de la propiedad',
                'verbose_name_plural': 'configuración de la propiedad',
                'db_table': 'property_settings',
            },
        ),
        migrations.CreateModel(
            name='AdditionalServiceInfo',
            fields=[
                ('id', models.CharField(choices=[('spa', 'Spa y masajes'), ('comida', 'Comida'), ('vinos', 'Vinos')], max_length=20, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image_url', models.TextField()),
                ('price_hint', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'información de servicio adicional',
                'verbose_name_plural': 'información de servicios adicionales',
                'db_table': 'additional_services_info',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('id__in', ['spa', 'comida', 'vinos'])), name='additional_services_info_id_check')],
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('icon_url', models.TextField()),
                ('sort_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='propiedades.amenitycategory')),
            ],
            options={
                'verbose_name': 'amenidad',
                'verbose_name_plural': 'amenidades',
                'db_table': 'amenities',
                'ordering': ['category__sort_order', 'sort_order'],
                'indexes': [models.Index(fields=['category', 'sort_order'], name='amenities_category_sort_idx')],
            },
        ),
    ]
