# Generated by Django 6.1.1 on 2026-09-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Super Administrador'), ('holder', 'Proveedor'), ('guest', 'Huésped')], default='guest', max_length=10),
        ),
    ]
