# Generated by Django 6.1.1 on 2026-09-04 04:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('completado', 'Completado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('provider', models.CharField(choices=[('simulado', 'Simulado'), ('stripe', 'Stripe')], default='simulado', max_length=20)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
