# Generated by Django 6.1.1 on 2026-09-04 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('reservaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reservaciones.reservation'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reservation'], name='payments_reservation_idx'),
        ),
    ]
