# Generated by Django 6.1.1 on 2026-09-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('completado', 'Completado'), ('reembolsado', 'Reembolsado'), ('na', 'No aplica / Exento')], default='pendiente', max_length=20),
        ),
    ]
