# Generated by Django 6.1.1 on 2026-09-04 04:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'disponibilidad de comida',
                'verbose_name_plural': 'disponibilidad de comida',
                'db_table': 'food_availability',
                'ordering': ['available_date'],
            },
        ),
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_type', models.CharField(choices=[('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Cena', 'Cena')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'menú',
                'verbose_name_plural': 'menús',
                'db_table': 'food_menus',
                'ordering': ['meal_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'vino',
                'verbose_name_plural': 'vinos',
                'db_table': 'wines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WinePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'paquete de vinos',
                'verbose_name_plural': 'paquetes de vinos',
                'db_table': 'wine_packages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpaAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_date', models.DateField()),
                ('available_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('masseuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='proveedores.spamasseuse')),
            ],
            options={
                'verbose_name': 'disponibilidad de spa',
                'verbose_name_plural': 'disponibilidad de spa',
                'db_table': 'spa_availability',
                'ordering': ['available_date', 'available_time'],
                'indexes': [models.Index(fields=['masseuse', 'available_date'], name='spa_avail_masseuse_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('masseuse', 'available_date', 'available_time'), name='spa_availability_unique_slot')],
            },
        ),
    ]
